name: Build Python Executable

# 手动构建运行
on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string

jobs:
  # 构建mac
  build-on-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'  # 替换为你的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Build executable
        run: |
          pyinstaller --onefile hello.py  

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
        with:
          tag_name: ${{ github.event.inputs.build_id }}  # 替换为你的发布标签名称
          release_name: Release ${{ github.event.inputs.build_id }}  # 替换为你的发布名称
          body: |
            first Release version on ${{ github.event.inputs.build_id }}.

      - name: Upload executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/hello  # 替换为生成的可执行文件路径
          asset_name: hello-macos-${{ github.event.inputs.build_id }}  # 替换为生成的可执行文件名称
          asset_content_type: application/octet-stream

  # 构建linux
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'  # 替换为你的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Build executable
        run: |
          pyinstaller --onefile hello.py  

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
        with:
          tag_name: ${{ github.event.inputs.build_id }}  # 替换为你的发布标签名称
          release_name: Release ${{ github.event.inputs.build_id }}  # 替换为你的发布名称
          body: |
            first Release version on ${{ github.event.inputs.build_id }}.

      - name: Upload executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/hello  # 替换为生成的可执行文件路径
          asset_name: hello-linux-${{ github.event.inputs.build_id }}  # 替换为生成的可执行文件名称
          asset_content_type: application/octet-stream

  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'  # 替换为你的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Build executable
        run: |
          pyinstaller --onefile hello.py  

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
        with:
          tag_name: ${{ github.event.inputs.build_id }}  # 替换为你的发布标签名称
          release_name: Release ${{ github.event.inputs.build_id }}  # 替换为你的发布名称
          body: |
            first Release version on ${{ github.event.inputs.build_id }}.

      - name: Upload executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/hello.exe  # 替换为生成的可执行文件路径
          asset_name: hello-${{ github.event.inputs.build_id }}.exe  # 替换为生成的可执行文件名称
          asset_content_type: application/octet-stream
