name: Pass Information Between Jobs

on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Set output value
        id: set_output
        run: echo "::set-output name=myOutput::Hello, World!"

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Get input value
        run: echo "Received input: ${{ needs.job1.outputs.myOutput }}"
