name: Pass Information Between Jobs

on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Set string data
        run: echo "Hello, World!" > my-data.txt
      - name: Upload data as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my-data.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Get environment variable
        run: echo Received input ${{ env.HELLO }}
      - name: Get input value
        run: echo "Received input ${{ needs.job1.outputs.myOutput }}"
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Read file content as variable
        id: read_file
        run: CONTENT=$(cat my-data.txt)
      - name: print content
        id: print
        run: echo "content:${{CONTENT}}"