name: Pass Information Between Jobs

on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Set string data
        run: echo "Hello, World!" > my-data.txt
      - name: Upload data as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my-data.txt

  job2:
    needs: job1
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Load environment variables from file
        shell: cmd
        run: |
          set /p CONTENT=<my-data.txt
          echo %CONTENT%
      - name: print content
        id: print
        run: |
        echo "content:${{ env.CONTENT }}"
        echo "content: %CONTENT%"